import { useMemo, type ReactNode } from "react";
import { BarChart3, CheckCircle2, Fuel, Gauge, ShieldCheck, Sparkles, TestTube2, Zap } from "lucide-react";
import { Bar, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useGridOptimizerResult, useMonteCarloResult, useNationalGridSnapshot } from "@/hooks/use-grid-backend";
import { optimizeFuelDispatch, calculateEnergyMix } from "@/services/fuel-optimization";

const SOURCE_COLORS = ["#4ade80", "#60a5fa", "#22d3ee", "#a78bfa", "#f59e0b", "#fb7185", "#f97316", "#94a3b8"];

export function GridEvidenceRoom() {
  const q = useNationalGridSnapshot();
  const mc = useMonteCarloResult({ simulations: 10_000, seed: 17_329 });
  const opt = useGridOptimizerResult({ simulations: 10_000, seed: 17_329 });
  const s = q.data;
  const fuel = useMemo(() => (s ? optimizeFuelDispatch(s) : null), [s]);
  const mix = useMemo(() => (s && fuel ? calculateEnergyMix(s, fuel) : []), [s, fuel]);
  const demand = s?.nationalDemandMw ?? 0;
  const renewable = s?.nationalRenewableGenerationMw ?? 0;
  const supply = s ? s.states.reduce((a, x) => a + x.energy.estimatedDemandMw + x.energy.supplyDemandGapMw, 0) : 0;
  const stock = fuel?.fuel.reduce((a, x) => a + x.stockMwh, 0) ?? 0;
  const after = fuel?.fuel.reduce((a, x) => a + x.stockAfterMwh, 0) ?? 0;
  const dist = s ? [
    { name: "Demand", mw: demand },
    { name: "Supply", mw: supply },
    { name: "Renewables", mw: renewable },
    { name: "Fuel", mw: fuel?.optimizedDispatchMw ?? 0 },
    { name: "Battery", mw: s.states.reduce((a, x) => a + x.energy.batteryAvailableMwh / 4, 0) },
  ] : [];
  const checks = [
    ["Weather → grid metrics", !!s],
    ["Energy model", !!s && demand > 0],
    ["Fuel optimisation", !!fuel],
    ["Monte Carlo", !!mc.data && mc.data.simulations === 10_000],
    ["Grid optimizer", !!opt.data],
  ];
  const ci = mc.data?.blackoutProbabilityCi95;
  const ciHalfWidth = ci ? (ci.high - ci.low) / 2 : 0;

  return <div className="min-h-screen bg-[#050812] text-foreground"><div className="mx-auto max-w-[1600px] px-5 py-10 md:px-10">
    <header className="mb-8 border-b border-[oklch(0.72_0.18_245/0.18)] pb-7"><div className="flex flex-wrap gap-3 text-[10px] font-mono tracking-[0.22em] text-muted-foreground"><span className="rounded border border-[oklch(0.85_0.21_145/0.35)] bg-[oklch(0.85_0.21_145/0.06)] px-2 py-1 text-[oklch(0.85_0.21_145)]">06 · EVIDENCE ROOM</span><span>MODEL SNAPSHOT · DETERMINISTIC MATH · SEEDED MONTE CARLO</span></div><h1 className="mt-4 max-w-4xl font-display text-4xl font-semibold md:text-6xl">From <span className="text-[oklch(0.85_0.21_145)]">energy mix</span> to the decision.</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-muted-foreground">A judge-friendly sequence: availability → demand/supply → stock → fuel optimisation → probabilistic risk → backend verification.</p></header>

    <Section n="00" title="Monte Carlo risk engine" sub="The hero metric is probabilistic risk, not a fabricated ML accuracy score."><Panel><div className="grid gap-5 xl:grid-cols-[1.15fr_1.85fr]"><div className="rounded-2xl border border-[oklch(0.85_0.21_145/0.24)] bg-[oklch(0.85_0.21_145/0.04)] p-6"><div className="font-mono text-[10px] tracking-[0.2em] text-[oklch(0.85_0.21_145)]">SEEDED MONTE CARLO</div><div className="mt-4 font-display text-5xl font-semibold md:text-7xl">{mc.data?.lossOfLoadProbability ?? "—"}%</div><div className="mt-2 text-sm">Loss-of-load probability</div><p className="mt-4 max-w-xl text-xs leading-5 text-muted-foreground">Estimated probability that modeled supply falls below modeled demand under the stated uncertainty distributions.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Stat a="SCENARIOS" b={mc.data?.simulations.toLocaleString() ?? "—"} c="seeded trials"/><Stat a="95% CI" b={ci ? `${ci.low}%–${ci.high}%` : "—"} c="probability interval"/><Stat a="PRECISION" b={ci ? `±${ciHalfWidth.toFixed(2)} pp` : "—"} c="sampling uncertainty"/><Stat a="EUE" b={mc.data ? `${mc.data.expectedUnservedEnergyMwh.toLocaleString()} MWh` : "—"} c="expected unserved energy"/><Stat a="PERFORMANCE" b={mc.data ? `${mc.data.simulationsPerSecond.toLocaleString()} /s` : "—"} c="measured throughput"/><Stat a="STABILITY GAP" b={mc.data ? `${mc.data.convergenceGapPercentagePoints} pp` : "—"} c="first-half vs second-half LOLP"/></div></div><p className="mt-4 text-[10px] text-muted-foreground">Monte Carlo does not have a classifier-style “accuracy %”. We report estimator precision, convergence stability and measured execution performance instead.</p></Panel></Section>

    <div className="mb-10 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Metric label="Demand" value={`${(demand / 1000).toFixed(1)} GW`} note="estimated national load" icon={<Gauge size={15} />} /><Metric label="Supply" value={`${(supply / 1000).toFixed(1)} GW`} note="available modeled supply" icon={<Zap size={15} />} /><Metric label="Renewables" value={`${(renewable / 1000).toFixed(1)} GW`} note={`${s?.nationalRenewablePenetrationPercent ?? 0}% penetration`} icon={<Sparkles size={15} />} /><Metric label="Fuel Stock" value={`${(after / 1000).toFixed(1)} GWh`} note={`${(stock / 1000).toFixed(1)} GWh before dispatch`} icon={<Fuel size={15} />} /><Metric label="Reserve Margin" value={`${s?.nationalReserveMarginPercent ?? 0}%`} note={opt.data ? `${opt.data.systemPriority} priority` : "optimizer pending"} icon={<ShieldCheck size={15} />} /></div>

    <Section n="01" title="Energy mix & demand/supply" sub="Every major source is visible before optimisation."><div className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><Panel><Title>Generation by source</Title><div className="h-[320px]"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={mix}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,.12)"/><XAxis dataKey="name" tick={{ fill:"#94a3b8", fontSize:10 }}/><YAxis unit=" MW" tick={{ fill:"#94a3b8", fontSize:10 }}/><Tooltip/><Bar dataKey="mw" name="Output" radius={[4,4,0,0]}>{mix.map((x,i)=><Cell key={x.name} fill={SOURCE_COLORS[i%8]}/>)}</Bar></ComposedChart></ResponsiveContainer></div></Panel><Panel><Title>System balance</Title><div className="h-[320px]"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={dist}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,.12)"/><XAxis dataKey="name" tick={{ fill:"#94a3b8", fontSize:10 }}/><YAxis unit=" MW" tick={{ fill:"#94a3b8", fontSize:10 }}/><Tooltip/><Bar dataKey="mw" name="Power" radius={[4,4,0,0]}>{dist.map((x,i)=><Cell key={x.name} fill={SOURCE_COLORS[i]}/>)}</Bar><Line dataKey="mw" stroke="#e2e8f0"/></ComposedChart></ResponsiveContainer></div><p className="text-xs text-muted-foreground">Read left-to-right: demand, supply, renewables, fuel and storage.</p></Panel></div></Section>

    <Section n="02" title="Fuel optimisation & stock availability" sub="Show exactly what is present, what is dispatched, and what remains."><div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><Panel><Title>Modeled fuel stock</Title>{fuel?.fuel.map(x=><div className="mb-5" key={x.id}><div className="mb-2 flex justify-between text-xs"><span>{x.label}</span><span className="font-mono text-muted-foreground">{x.stockAfterMwh.toLocaleString()} / {x.stockMwh.toLocaleString()} MWh</span></div><div className="h-2 rounded-full bg-white/5"><div className="h-full rounded-full bg-[oklch(0.85_0.21_145)]" style={{width:`${Math.max(2,x.stockAfterMwh/x.stockMwh*100)}%`}}/></div><div className="mt-1 flex justify-between text-[9px] font-mono text-muted-foreground"><span>DISPATCH {x.recommendedDispatchMw} MW</span><span>{(x.stockAfterMwh/x.stockMwh*100).toFixed(1)}% REMAINING</span></div></div>)}<div className="grid grid-cols-2 gap-3"><Stat a="DISPATCH NEED" b={`${((fuel?.requiredDispatchMw??0)/1000).toFixed(2)} GW`}/><Stat a="OPTIMIZED" b={`${((fuel?.optimizedDispatchMw??0)/1000).toFixed(2)} GW`}/><Stat a="MODELED COST" b={`₹${((fuel?.estimatedCost??0)/1e6).toFixed(1)}M`}/><Stat a="CARBON" b={`${((fuel?.estimatedCarbonKg??0)/1000).toFixed(1)} t`}/></div><p className="mt-4 text-[10px] text-muted-foreground">Stock is modeled energy-equivalent reserve, not live inventory.</p></Panel><Panel><Title>Optimisation formula</Title><div className="rounded-xl border border-[oklch(0.85_0.21_145/0.22)] bg-black/20 p-5 font-mono text-xs leading-7">Residual demand = Demand − Renewables − Battery power<br/>Dispatchᵢ = min(Residual demand, Stockᵢ, Max dispatchᵢ)<br/>Total cost = Σ(Dispatchᵢ × Marginal costᵢ)<br/><span className="text-[oklch(0.85_0.21_145)]">Choose the lowest-cost feasible dispatch while preserving stock.</span></div>{fuel?.fuel.map((x,i)=><div key={x.id} className="mt-2 grid grid-cols-[28px_1fr_auto] gap-3 rounded-lg border border-white/5 p-3 text-xs"><span className="font-mono text-muted-foreground">0{i+1}</span><span>{x.label}</span><span className="font-mono text-[oklch(0.85_0.21_145)]">₹{x.marginalCostPerMwh.toLocaleString()}/MWh</span></div>)}</Panel></div></Section>

    <Section n="03" title="Monte Carlo distributions" sub="Show uncertainty rather than hiding it behind one point estimate."><div className="grid gap-5 lg:grid-cols-3"><Distribution title="Demand" p={mc.data?.demandPercentiles}/><Distribution title="Renewable generation" p={mc.data?.renewableGenerationPercentiles}/><Panel><Title>Loss of load</Title><div className="grid place-items-center"><div className="relative h-44 w-44"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{v:mc.data?.lossOfLoadProbability??0},{v:100-(mc.data?.lossOfLoadProbability??0)}]} dataKey="v" innerRadius={55} outerRadius={78}><Cell fill="#fb7185"/><Cell fill="#1e293b"/></Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 grid place-items-center text-center font-display text-2xl">{mc.data?.lossOfLoadProbability??0}%<span className="block font-mono text-[9px] text-muted-foreground">LOLP</span></div></div><p className="text-center text-xs text-muted-foreground">{mc.data?.simulations??0} seeded scenarios · EUE {mc.data?.expectedUnservedEnergyMwh??0} MWh</p></div></Panel></div></Section>

    <Section n="04" title="Backend verification" sub="Run the same core checks from the terminal; keep the results visible to the panel."><Panel><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{checks.map(([name,pass])=><div key={String(name)} className="flex items-center justify-between rounded-lg border border-white/5 bg-black/20 p-4"><span className="text-sm">{String(name)}</span>{pass?<CheckCircle2 size={20} className="text-[oklch(0.85_0.21_145)]"/>:<TestTube2 size={20} className="animate-pulse text-[oklch(0.82_0.17_75)]"/>}</div>)}</div><div className="mt-5 rounded-lg border border-[oklch(0.72_0.18_245/0.15)] bg-black/20 p-4 font-mono text-[10px] text-muted-foreground">Backend test: <span className="text-foreground">python -m unittest discover -s backend -p "test_*.py" -v</span><br/>Server: <span className="text-foreground">python backend/main.py</span> · port 8010 · /health</div></Panel></Section>
  </div></div>;
}
function Section({n,title,sub,children}:{n:string;title:string;sub:string;children:ReactNode}){return <section className="mb-12"><div className="mb-5 flex gap-4"><span className="font-mono text-[10px] text-[oklch(0.72_0.18_245)]">{n}</span><div><h2 className="font-display text-2xl font-semibold md:text-3xl">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{sub}</p></div></div>{children}</section>}
function Panel({children}:{children:ReactNode}){return <div className="rounded-2xl border border-white/5 bg-[oklch(0.12_0.025_255/0.75)] p-5 shadow-[0_0_35px_-18px_oklch(0.72_0.18_245/0.5)] md:p-6">{children}</div>}
function Title({children}:{children:ReactNode}){return <div className="mb-5 flex items-center gap-2 font-mono text-[10px] tracking-[0.18em] text-muted-foreground"><BarChart3 size={13}/>{children}</div>}
function Metric({label,value,note,icon}:{label:string;value:string;note:string;icon:ReactNode}){return <div className="rounded-xl border border-white/5 bg-black/15 p-4"><div className="flex items-center gap-2 font-mono text-[9px] tracking-[0.15em] text-muted-foreground">{icon}{label}</div><div className="mt-2 font-display text-2xl">{value}</div><div className="mt-1 text-[10px] text-muted-foreground">{note}</div></div>}
function Stat({a,b,c}:{a:string;b:string;c?:string}){return <div className="rounded-xl border border-white/5 bg-black/20 p-3"><div className="font-mono text-[8px] tracking-[0.15em] text-muted-foreground">{a}</div><div className="mt-1 font-display text-lg">{b}</div>{c&&<div className="text-[9px] text-muted-foreground">{c}</div>}</div>}
function Distribution({title,p}:{title:string;p?:{p5:number;p50:number;p95:number}}){return <Panel><Title>{title}</Title><div className="grid grid-cols-3 gap-3"><Stat a="P05" b={p?p.p5.toLocaleString():"—"} c="MW"/><Stat a="P50" b={p?p.p50.toLocaleString():"—"} c="MW"/><Stat a="P95" b={p?p.p95.toLocaleString():"—"} c="MW"/></div><div className="mt-5 h-2 rounded-full bg-gradient-to-r from-[oklch(0.68_0.24_25)] via-[oklch(0.82_0.17_75)] to-[oklch(0.85_0.21_145)]"/></Panel>}
